config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
]

website/urls.py
from django.urls import path
from . import views

app_name = "website"

urlpatterns = [
    path("", views.index, name="index"),
    path("sections/<int:num>", views.section, name="section"),


    path('home', views.home_page_view, name='home'),
    path('musica', views.musica_page_view, name='musica'),
    path('Toys', views.Toys_page_view, name='Toys'),
    path('sobre', views.sobre_page_view, name='sobre'),
    path('quizz', views.quizz_page_view, name='quizz'),
    path('quinta', views.quinta_page_view, name='quinta'),
    path('jogos', views.jogos_page_view, name='jogos'),
    path('comentarios/', views.novo_comentario_view, name='comentarios'),

    path('nova/', views.nova_tarefa_view, name='nova'),
    path('contactos/', views.contactos_page_view, name='contactos'),
    path('edita/<int:contacto_id>', views.edita_tarefa_view, name='edita'),
    path('apaga/<int:contacto_id>', views.apaga_tarefa_view, name='apaga')
]

website/models.py
from django.db import models


class Contacto(models.Model):
    Nome = models.CharField(max_length=200)
    email = models.CharField(max_length=200)
    prioridade = models.IntegerField(default=1)
    concluido = models.BooleanField(default=False)
    criado = models.DateTimeField(auto_now_add=True)

class Comentario(models.Model):
    Nome = models.CharField(max_length=200)
    comentario = models.CharField(max_length=1000)

website/forms.py
from django.forms import ModelForm, forms
from .models import Contacto, Comentario


class ContactoForm(ModelForm):
    class Meta:
        model = Contacto
        fields = '__all__'

class ComentarioForm(ModelForm):
    class Meta:
        model = Comentario
        fields = '__all__'

website/views.py
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.shortcuts import render
from django.urls import reverse

from .models import Contacto
from .forms import ContactoForm, ComentarioForm

def index(request):
    return render(request,"website/singlepage.html")

text = ["Page 1 text","Page 2 text","Page 3 text"]

def section(request, num):
    if 1 <= num <= 3:
        return HttpResponse(text[num-1])
    else:
        raise Http404("No such section")
# Create your views here.


def home_page_view(request):
    context = {'website': Contacto.objects.all()}
    return render(request, 'website/home.html', context)


def nova_tarefa_view(request):
    form = ContactoForm(request.POST or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('website:home'))

    context = {'form': form}

    return render(request, 'website/nova.html', context)

def novo_comentario_view(request):
    form = ComentarioForm(request.POST or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('website:home'))

    context = {'form': form}

    return render(request, 'website/comentarios.html', context)

def edita_tarefa_view(request, contacto_id):
    contacto = Contacto.objects.get(id=contacto_id)
    form = ContactoForm(request.POST or None, instance=contacto)

    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('website:home'))

    context = {'form': form, 'contacto_id': contacto_id}
    return render(request, 'website/edita.html', context)


def apaga_tarefa_view(request, contacto_id):
    Contacto.objects.get(id=contacto_id).delete()
    return HttpResponseRedirect(reverse('website:home'))

def contactos_page_view(request):
	return render(request, 'website/contactos.html')
def musica_page_view(request):
	return render(request, 'website/Musica.html')

def Toys_page_view(request):
	return render(request, 'website/Toys.html')

def sobre_page_view(request):
	return render(request, 'website/sobre.html')

def quizz_page_view(request):
	return render(request, 'website/quizz.html')

def quinta_page_view(request):
	return render(request, 'website/quinta.html')

def jogos_page_view(request):
	return render(request, 'website/jogos.html')

website/templates/website/Jogos.html
<!DOCTYPE html>
<html lang="pt">
    <head>
         {% load static %}
        <link rel="stylesheet" href="{% static 'website/css/estilos.css' %}">
        <link href='https://fonts.google.com/css?family=Sofia' rel='stylesheet'>
        <meta name="keywords" content="HTML,CSS">
        <meta name="Site para Crianças" content="Website sobre Crianças">
        <link rel="shortcut icon" type="image/x-icon" href="images/PNG Image.ico"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <title>Jogos</title>
    </head>

    <body background="{% static 'website/images/jogos_fundo.jpg' %}">
        <div class="logo_nav">
            <a href="#"><img src="{% static 'website/images/logo.png' %}"></a>
        </div>  
        <div class="grid-container">
            <div class="Header"> 
                <nav class="top_nav">
                    <ul>
                         <li><a href="{% url 'website:home' %}">Casa</a></li>
                      <li><a href="{% url 'website:Toys' %}">Personagens</a></li>
                      <li><a href="{% url 'website:jogos' %}">Jogos</a></li>
                      <li><a href="{% url 'website:quizz' %}">Quizz</a></li>
                      <li><a href="{% url 'website:musica' %}">Musica</a></li>
                      <li><a href="{% url 'website:quinta' %}">Quinta</a></li>
                      <li><a href="{% url 'website:sobre' %}">Sobre</a></li>
                           <li><a href="{% url 'website:comentarios' %}">Comentarios</a></li>
                        <li><a href="{% url 'website:contactos' %}">Contactos</a></li>
   <li><a href="{% url 'website:index' %}">Single Page</a></li>
                    </ul>
                </nav>
            </div>
            <div class="Menu">

                <a id="pato_boneco_toys" href="#"><img class="pato_jogos" src="{% static 'website/images/pato_donnald_boneco-removebg-preview.png' %}"  onmouseover="mickey.play()"></a>
            </div>
            <div class="Main">
                <figure class="Jogos">
                    <a href="https://www.miniclip.com/games/bubble-trouble/pt/#t-c-f-C">

                        <img id="bouble" src="{% static 'website/images/bouble.png' %}" >
                    </a>
                </figure>
                <figure class="Jogos">
                    <a href="https://www.miniclip.com/games/flow-mania/pt/#t-w-c-C">

                        <img id="flow_mania" src="{% static 'website/images/flow-mania.png' %}"  >
                    </a>
                   
                </figure>
                <figure class="Jogos">
                    <a href="https://www.miniclip.com/games/cut-the-rope-2/pt/#t-w-c-C">

                        <img id="cut_rope" src="{% static 'website/images/cut_rope.webp' %}" >
                    </a>
                    
                </figure>
                <figure class="Jogos">
                    <a href="https://www.miniclip.com/games/2048/pt/#t-c-f-C">

                        <img id="doismil" src="{% static 'website/images/2048.png' %}"  >
                    </a>
                  
                </figure>
                <figure class="Jogos">
                    <a href="https://www.miniclip.com/games/agar-io/pt/#t-w-t-C">

                        <img id="agario" src="{% static 'website/images/agario.png' %}" >
                    </a>
                </figure>
            </div>  
            <div class="Footer">Divirtam-se</div>
        </div>
    </body>
</html>
<!DOCTYPE html>

website/templates/website/Musica.html
<!DOCTYPE html>
<html id="Musica_html" lang="pt">
    <head>
        {% load static %}
        <link rel="stylesheet" href="{% static 'website/css/estilos.css' %}">
        <link href='https://fonts.google.com/css?family=Sofia' rel='stylesheet'>
        <meta name="keywords" content="HTML,CSS">
        <link rel="stylesheet" href="estilos.css">
        <meta name="Site para Crianças" content="Website sobre Crianças">
        <link rel="shortcut icon" type="image/x-icon" href="images/PNG Image.ico"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Musica</title>
    </head>
    <body background="{% static 'website/images/musica_fundo.png' %}">
        <div class="logo_nav">
            <a href="#"><img src="{% static 'website/images/logo.png' %}"></a>
        </div>  
        <div class="grid-container">
            <div class="Header"> 
                <nav class="top_nav">
                    <ul>
                         <li><a href="{% url 'website:home' %}">Casa</a></li>
                      <li><a href="{% url 'website:Toys' %}">Personagens</a></li>
                      <li><a href="{% url 'website:jogos' %}">Jogos</a></li>
                      <li><a href="{% url 'website:quizz' %}">Quizz</a></li>
                      <li><a href="{% url 'website:musica' %}">Musica</a></li>
                      <li><a href="{% url 'website:quinta' %}">Quinta</a></li>
                      <li><a href="{% url 'website:sobre' %}">Sobre</a></li>
                           <li><a href="{% url 'website:comentarios' %}">Comentarios</a></li>
                        <li><a href="{% url 'website:contactos' %}">Contactos</a></li>
   <li><a href="{% url 'website:index' %}">Single Page</a></li>
                    </ul>
                </nav>
            </div>
            <div class="Menu">
                <a id="mickey_guitarra" href="#"><img class="mickeyguitarra" src="{% static 'website/images/mickey_guitarra.png' %}" onmouseover="mickey.play()"></a>
            </div>
            <div class="Main">
                <figure class="musica">
                        <img id="guitarra" src="{% static 'website/images/guitarra.png' %}">
                        <audio id="guitarra_audio"  controls>
                            <source src="{% static 'website/audios/guitarra.mp3' %}" type="audio/ogg">
                            <source src="{% static 'website/audios/guitarra.mp3' %}" type="audio/mpeg">
                        </audio>
                        <figcaption>Guitarra</figcaption>
                </figure>
                <figure class="musica">
                    <img id="piano" src="{% static 'website/images/piano (1).png' %}"  >
                    <audio id="piano_audio"  controls>
                        <source src="{% static 'website/audios/piano.mp3' %}"type="audio/ogg">
                        <source src="{% static 'website/audios/piano.mp3' %}" type="audio/mpeg">
                    </audio>
                    <figcaption>Piano</figcaption>                                
                </figure>
                <figure class="musica">

                    <img id="bateria" src="{% static 'website/images/bateria.png' %}"  >
                    <audio id="bateria_audio"  controls>
                        <source src="{% static 'website/audios/bateria.mp3' %}" type="audio/ogg">
                        <source src="{% static 'website/audios/bateria.mp3' %}" type="audio/mpeg">
                    </audio>
                    <figcaption>Bateria</figcaption>
            </figure>
                <figure class="musica">

                        <img id="trompete" src="{% static 'website/images/trompete.png' %}">
                        <audio id="trompete_audio"  controls>
                            <source src="{% static 'website/audios/trumpet.mp3' %}" type="audio/ogg">
                            <source src="{% static 'website/audios/trumpet.mp3' %}" type="audio/mpeg">
                        </audio>  
                        <figcaption>Trompete</figcaption>
                </figure>
                
            </div>  
            <div class="Footer">Divirtam-se</div>
        </div>
    </body>
</html>
<!DOCTYPE html>

website/templates/website/Toys.html
<!DOCTYPE html>
<html id="personagens_html">
    <head>
        {% load static %}
      <link href='https://fonts.google.com/css?family=Sofia' rel='stylesheet'>
      <meta name="keywords" content="HTML,CSS">
        <link rel="stylesheet" href="{% static 'website/css/estilos.css' %}">
        <meta name="Site para Crianças" content="Website para Crianças">
        <link rel="shortcut icon" type="image/x-icon" href="images/PNG Image.ico"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Personagens</title>
        <script>
            var minie=new Audio()
            minie.src="{% static 'website/audios/minnie.mp3' %}"

            var margarida=new Audio()
            margarida.src="{% static 'website/audios/margarida.mp3' %}"

            var pluto=new Audio()
            pluto.src="{% static 'website/audios/pluto.mp3' %}"

            var pato=new Audio()
            pato.src="{% static 'website/audios/pato.mp3' %}"

            var pateta=new Audio()
            pateta.src="{% static 'website/audios/pateta.mp3' %}"

            var patinhas=new Audio()
            patinhas.src="{% static 'website/audios/patinhas.mp3' %}"

            var bugs=new Audio()
            bugs.src="{% static 'website/audios/bugs.mp3' %}"

            var daffy=new Audio()
            daffy.src="{% static 'website/audios/daffy.mp3' %}"

            var mickey=new Audio()
            mickey.src="{% static 'website/audios/mickey.mp3' %}"

            var winnie=new Audio()
            winnie.src="{% static 'website/audios/winnie.mp3' %}"
        </script>
    </head>
    <body background="{% static 'website/images/teste.jpg' %}">
        <div class="logo_nav">
            <a href="#"><img src="{% static 'website/images/logo.png' %}"></a>
        </div>  
        <div class="grid-container">
            <div class="Header"> 
                <nav class="top_nav">
                    <ul>
                      <li><a href="{% url 'website:home' %}">Casa</a></li>
                      <li><a href="{% url 'website:Toys' %}">Personagens</a></li>
                      <li><a href="{% url 'website:jogos' %}">Jogos</a></li>
                      <li><a href="{% url 'website:quizz' %}">Quizz</a></li>
                      <li><a href="{% url 'website:musica' %}">Musica</a></li>
                      <li><a href="{% url 'website:quinta' %}">Quinta</a></li>
                      <li><a href="{% url 'website:sobre' %}">Sobre</a></li>
                           <li><a href="{% url 'website:comentarios' %}">Comentarios</a></li>
                        <li><a href="{% url 'website:contactos' %}">Contactos</a></li>
                                <li><a href="{% url 'website:index' %}">Single Page</a></li>

                    </ul>
                </nav>
            </div>
            <div class="Menu">
                <a id="mickey_boneco_toys" href="#"><img class="mickey_personagens" src="{% static 'website/images/Mickey_Mouse.png' %}"></a>
            </div>
            <div class="Main_toys">
                <figure class="column">
                    <img id="minnie_toys" src="{% static 'website/images/minnie_cara.png' %}" background-image="{% static 'images/vermelho.png' %}" onmouseover="minie.play(),pluto.pause()
                    ,margarida.pause(),pato.pause(),pateta.pause(),patinhas.pause(),bugs.pause(),daffy.pause(),mickey.pause(),winnie.pause()">
                </figure>
                  <figure class="column">
                    <img id="margarida_toys" src="{% static 'website/images/margarida_cara.png' %}"  onmouseover="margarida.play(),pluto.pause()
                    ,minie.pause(),pato.pause(),pateta.pause(),patinhas.pause(),bugs.pause(),daffy.pause(),mickey.pause(),winnie.pause()" >
                  </figure>
                  <figure class="column">
                    <img id="pluto_toys" src="{% static 'website/images/pluto_face.png' %}" onmouseover="pluto.play(), margarida.pause()
                    ,minie.pause(),pato.pause(),pateta.pause(),patinhas.pause(),bugs.pause(),daffy.pause(),mickey.pause(),winnie.pause()" >
                  </figure>
                  <figure class="column">
                    <img id="pato_toys" src="{% static 'website/images/pato_donnald_cara.png' %}"  onmouseover="pato.play(), pluto.pause(),pluto.pause()
                    ,minie.pause(),margarida.pause(),pateta.pause(),patinhas.pause(),bugs.pause(),daffy.pause(),mickey.pause(),winnie.pause()" >
                  </figure>
                  <figure class="column">

                    <img id="pateta_toys" src="{% static 'website/images/pateta_cara.png' %}"  onmouseover="pateta.play(),pluto.pause()
                    ,minie.pause(),margarida.pause(),pato.pause(),patinhas.pause(),bugs.pause(),daffy.pause(),mickey.pause(),winnie.pause()">
                  </figure>
                  <figure class="column">
                    <img id="patinhas_toys" src="{% static 'website/images/patinhas_cara.png' %}"  onmouseover="patinhas.play(),pluto.pause()
                    ,minie.pause(),margarida.pause(),pateta.pause(),pato.pause(),bugs.pause(),daffy.pause(),mickey.pause(),winnie.pause()">
                  </figure>
                  <figure class="column">
                    <img id="bugs_toys" src="{% static 'website/images/bugs_bunny_face.png' %}"  onmouseover="bugs.play(),pluto.pause()
                    ,minie.pause(),margarida.pause(),pateta.pause(),patinhas.pause(),pato.pause(),daffy.pause(),mickey.pause(),winnie.pause()">
                  </figure>
                  <figure class="column">

                    <img id="daffy_toys" src="{% static 'website/images/daffy_duck_face.png' %}"  onmouseover="daffy.play(),pluto.pause()
                    ,minie.pause(),margarida.pause(),pateta.pause(),patinhas.pause(),bugs.pause(),pato.pause(),mickey.pause(),winnie.pause()" >
                  </figure>
                  <figure class="column">
                    <img id="tom_toys" src="{% static 'website/images/mickey_cara.png' %}" onmouseover="mickey.play(),pluto.pause()
                    ,minie.pause(),margarida.pause(),pateta.pause(),patinhas.pause(),bugs.pause(),daffy.pause(),pato.pause(),winnie.pause()">
                  </figure>
                  <figure class="column">
                    <img id="jerry_toys" src="{% static 'website/images/winnie_face.png' %}" onmouseover="winnie.play(),pluto.pause()
                    ,minie.pause(),margarida.pause(),pateta.pause(),patinhas.pause(),bugs.pause(),daffy.pause(),mickey.pause(),pato.pause()">
                  </figure> 
            </div>  
            <div class="Footer">Divirtam-se</div>
        </div>
    </body>
</html>
<!DOCTYPE html>

website/templates/website/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
        {% load static %}

    <meta charset="UTF-8">
    <title>Website para crianças</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <header class="jumbotron text-center">
        <a href="{% url 'website:home' %}">Casa</a>
        <a href="{% url 'website:Toys' %}">Personagens</a>
        <a href="{% url 'website:jogos' %}">Jogos</a>
        <a href="{% url 'website:quizz' %}">Quizz</a>
        <a href="{% url 'website:musica' %}">Musica</a>
        <a href="{% url 'website:quinta' %}">Quinta</a>
        <a href="{% url 'website:sobre' %}">Sobre</a>
        <a href="{% url 'website:comentarios' %}">Comentarios</a>
        <a href="{% url 'website:contactos' %}">Contactos</a>
        <a href="{% url 'website:index' %}">Single Page</a>
    </header>

    <main class="container text-center">
    {% block main %}

    {% endblock %}
    </main>
    <footer></footer>
</body>
</html>

website/templates/website/comentarios.html
{% extends 'website/base.html' %}

{% block main %}
<h3>Novo Comentario</h3>

    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}

        <a href="{% url 'website:home' %}" role="button" class="btn btn-warning">Cancelar</a>
        <input type="submit" value="Gravar" class="btn btn-success" >
    </form>

{% endblock %}

website/templates/website/contactos.html
{% extends 'website/base.html' %}

{% block main %}
    {% for contacto in website %}
        <p>
            <span class="info">
                ({{ contacto.criado.day }}/{{ contacto.criado.month }})
                {% if contacto.prioridade == 1 %}
                    🟢
                {% elif contacto.prioridade == 2 %}
                    🟡
                {% else %}
                     🔴
                {% endif %}
            </span>
            {% if contacto.concluido == True %}
                <del>{{ contacto.titulo }}</del>
            {% else %}
                {{ contacto.titulo }}
            {% endif %}
            <a href="{% url 'website:edita' contacto.id %}" class="btn btn-warning  btn-sm" style="float: right; margin-right: 10px">
                Editar
            </a>
        </p>
   {% endfor %}
        <a href="{% url 'website:nova' %}" class="btn btn-success btn-block">+ Novo Contacto</a>
{% endblock %}

website/templates/website/edita.html
{% extends 'website/base.html' %}

{% block main %}
<h3>Contacto</h3>
    <form action="{% url 'website:edita' contacto_id %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}

        <a href="{% url 'website:home' %}" role="button" class="btn btn-warning">Cancelar</a>
        <input type="submit" value="Gravar" class="btn btn-success" >
        <a href="{% url 'website:apaga' contacto_id %}" role="button" class="btn btn-danger">Apagar</a>
    </form>

{% endblock %}

website/templates/website/home.html
<!DOCTYPE html>
<html id="Home_html" lang="pt">
      <head>
         {% load static %}
        <link rel="stylesheet" href="{% static 'website/css/estilos.css' %}">
        <link href='https://fonts.google.com/css?family=Sofia' rel='stylesheet'>
        <meta name="keywords" content="HTML,CSS">
        <meta name="Site para Crianças" content="Website sobre Crianças">
        <link rel="shortcut icon" type="image/x-icon" href="images/PNG Image.ico"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <title>Casa</title>
    </head>
    <audio autoplay  >
        <source src="audios/home.wav" type="audio/ogg">
        <source src="audios/home.wav" type="audio/mpeg">
    </audio>

      <body background="{% static 'website/images/fundo.jpg' %}">
        <div class="logo_nav">
             <a href="#"><img src="{% static 'website/images/logo.png' %}"></a>
        </div>  
        <div class="grid-container">
            <div class="Header"> 
                <nav class="top_nav">
                    <ul>
                        <li><a href="{% url 'website:home' %}">Casa</a></li>
                      <li><a href="{% url 'website:Toys' %}">Personagens</a></li>
                      <li><a href="{% url 'website:jogos' %}">Jogos</a></li>
                      <li><a href="{% url 'website:quizz' %}">Quizz</a></li>
                      <li><a href="{% url 'website:musica' %}">Musica</a></li>
                      <li><a href="{% url 'website:quinta' %}">Quinta</a></li>
                      <li><a href="{% url 'website:sobre' %}">Sobre</a></li>
                        <li><a href="{% url 'website:comentarios' %}">Comentarios</a></li>
                        <li><a href="{% url 'website:contactos' %}">Contactos</a></li>
                                <li><a href="{% url 'website:index' %}">Single Page</a></li>


                    </ul>
                </nav>
            </div>
            <div class="Menu">

                <a  class="minnie_menu" href="quinta.html"><img class="minnie_casa" src="{% static 'website/images/Minnie_Mouse_pose_-removebg-preview.png' %}" ></a>
            </div>
            <div class="Main">
                <figure class="main1">
                    <a id="mickey_menu" href="Home.html"><img class="mickey_casa"  src="{% static 'website/images/Mickey_Mouse.png' %}" ></a>

                </figure>
                <figure class="main1">
                    <a id="pato_menu" href="{% url 'website:Toys' %}"><img class="pato_casa" src="{% static 'website/images/pato_donnald_boneco-removebg-preview.png' %}"></a>
                </figure>
                <figure class="main1">
                    <a id="pluto_menu" href="{% url 'website:jogos' %}"><img class="pluto_casa"  src="{% static 'website/images/Pluto_boneco.png' %}"></a>
                </figure> 
                <figure class="main1">
                    <a id="winnie_menu" href="{% url 'website:quizz' %}"><img class="winnie_casa" src="{% static 'website/images/winnie_boneco.png' %}"></a>
                </figure> 
            </div>  
            <div class="Footer">Divirtam-se</div>
        </div>
    </body>
</html>
<!DOCTYPE html>

website/templates/website/nova.html
{% extends 'website/base.html' %}

{% block main %}
<h3>Novo Contacto</h3>

    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}

        <a href="{% url 'website:home' %}" role="button" class="btn btn-warning">Cancelar</a>
        <input type="submit" value="Gravar" class="btn btn-success" >
    </form>

{% endblock %}

website/templates/website/quinta.html
<!DOCTYPE html>
<html id="Home_html" lang="pt">
    <head>
         {% load static %}
        <link rel="stylesheet" href="{% static 'website/css/estilos.css' %}">
        <link href='https://fonts.google.com/css?family=Sofia' rel='stylesheet'>
        <meta name="keywords" content="HTML,CSS">
        <meta name="Site para Crianças" content="Website sobre Crianças">
        <link rel="shortcut icon" type="image/x-icon" href="images/PNG Image.ico"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <title>Quinta</title>
        <script>
            var cavalo=new Audio()
            cavalo.src="{% static 'website/audios/cavalo.wav' %}"

            var vaca=new Audio()
            vaca.src="{% static 'website/audios/vacas.wav' %}"

            var ovelha=new Audio()
            ovelha.src="{% static 'website/audios/ovelhas.wav' %}"

            var burro=new Audio()
            burro.src="{% static 'website/audios/burro.mp3' %}"

            var porco=new Audio()
            porco.src="{% static 'website/audios/porco.mp3' %}"

            var coelho=new Audio()
            coelho.src="{% static 'website/audios/coelho.mp3' %}"

            var galinha=new Audio()
            galinha.src="{% static 'website/audios/galinhas.mp3' %}"

            var galo=new Audio()
            galo.src="{% static 'website/audios/galo.mp3' %}"

            var cao=new Audio()
            cao.src="{% static 'website/audios/cao.mp3' %}"
        </script>
    </head>
    <body background="{% static 'website/images/animais_fundo.jpg' %}" >
        <div class="logo_nav">

            <a href="#"><img src="{% static 'website/images/logo.png' %}"></a>
        </div>  
        <div class="grid-container">
            <div class="Header"> 
                <nav class="top_nav">
                    <ul>
                         <li><a href="{% url 'website:home' %}">Casa</a></li>
                      <li><a href="{% url 'website:Toys' %}">Personagens</a></li>
                      <li><a href="{% url 'website:jogos' %}">Jogos</a></li>
                      <li><a href="{% url 'website:quizz' %}">Quizz</a></li>
                      <li><a href="{% url 'website:musica' %}">Musica</a></li>
                      <li><a href="{% url 'website:quinta' %}">Quinta</a></li>
                      <li><a href="{% url 'website:sobre' %}">Sobre</a></li>
                        <li><a href="{% url 'website:comentarios' %}">Comentarios</a></li>
                        <li><a href="{% url 'website:contactos' %}">Contactos</a></li>
   <li><a href="{% url 'website:index' %}">Single Page</a></li>
                    </ul>
                </nav>
            </div>
            <div class="Menu">
            </div>
            <div class="Main">
                <a id="cavalo" onmouseover="cavalo.play()">.</a>
                <a id="vaca" onmouseover="vaca.play()">.</a>
                <a id="ovelha" onmouseover="ovelha.play()">.</a>
                <a id="burro" onmouseover="burro.play()">.</a>
                <a id="porco" onmouseover="porco.play()">.</a>
                <a id="coelho" onmouseover="coelho.play()">.</a>
                <a id="galinha" onmouseover="galinha.play()">.</a>
                <a id="galo" onmouseover="galo.play()">.</a>
                <a id="cao" onmouseover="cao.play()">.</a>
            </div>  
            <div class="Footer" >Divirtam-se</div>
        </div>
    </body>
</html>
<!DOCTYPE html>